version: '3'
services:
  push_python:
    image: j-ha/gpnpush:latest
    container_name: push_python
    networks:
      - badge_push
    volumes:
      - ./settings.py.docker:/usr/src/app/settings.py
    labels:
      traefik.backend: 'gpnpush'
      traefik.docker.network: 'badge_push'
      traefik.frontend.rule: 'Host:gulasch.localhost'
      traefik.enable: 'true'
      traefik.port: '5000'

  push_database:
    image: postgres
    container_name: push_database
    networks:
      - badge_push
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    labels:
      traefik.enable: 'false'

  traefik:
    image: traefik
    command: --docker --InsecureSkipVerify=true
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    networks:
      - badge_push
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./traefik.toml:/traefik.toml
      #- ./certs:/certs
    labels:
      traefik.enable: 'false'


networks:
  badge_push:
    driver: bridge